{
 "title": "Trakt Tracker Dashboard",
 "tags": [
  "trakt",
  "media",
  "stats",
  "tracker"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "bucket_raw", "query": "trakt_raw" },
   { "name": "bucket_agg", "query": "trakt_agg" }
  ]
 },
 "panels": [
  {
   "title": "Total Minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trakt_agg\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_daily\")\n  |> filter(fn: (r) => r[\"_field\"] == \"watch_minutes_total\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"all\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Total Hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trakt_agg\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_daily\")\n  |> filter(fn: (r) => r[\"_field\"] == \"watch_minutes_total\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"all\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 60.0 }))"
    }
   ]
  },
  {
   "title": "Total Plays",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trakt_agg\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_daily\")\n  |> filter(fn: (r) => r[\"_field\"] == \"events_count\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"all\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Total Movies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trakt_agg\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_daily\")\n  |> filter(fn: (r) => r[\"_field\"] == \"events_count\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"movie\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Total Episodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trakt_agg\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_daily\")\n  |> filter(fn: (r) => r[\"_field\"] == \"events_count\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"episode\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Rewatches",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trakt_agg\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_daily\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rewatch_events_count\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"all\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Plays Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"trakt_agg\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_daily\")\n  |> filter(fn: (r) => r[\"_field\"] == \"events_count\")\n  |> filter(fn: (r) => r[\"media_type\"] != \"all\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> drop(columns: [\"_field\"])\n  |> rename(columns: {\"media_type\": \"_field\"})"
    }
   ]
  },
  {
   "title": "Distribution by Media Type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trakt_agg\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_daily\")\n  |> filter(fn: (r) => r[\"_field\"] == \"events_count\")\n  |> filter(fn: (r) => r[\"media_type\"] != \"all\")\n  |> group(columns: [\"media_type\"])\n  |> sum()\n  |> group()\n  |> map(fn: (r) => ({ _time: now(), _field: if r.media_type == \"movie\" then \"Movies\" else \"Episodes\", _value: r._value }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Daily Plays",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"trakt_agg\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_daily\")\n  |> filter(fn: (r) => r[\"_field\"] == \"events_count\")\n  |> filter(fn: (r) => r[\"media_type\"] != \"all\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> drop(columns: [\"_field\"])\n  |> rename(columns: {\"media_type\": \"_field\"})"
    }
   ]
  },
  {
   "title": "Top 10 Watched Shows",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"trakt_raw\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_event\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"episode\")\n  |> filter(fn: (r) => r[\"_field\"] == \"show_title\" or r[\"_field\"] == \"trakt_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"show_title\"])\n  |> count(column: \"trakt_id\")\n  |> group()\n  |> rename(columns: {\"show_title\": \"Show\", \"trakt_id\": \"Plays\"})\n  |> keep(columns: [\"Show\", \"Plays\"])\n  |> sort(columns: [\"Plays\"], desc: true)\n  |> limit(n: 10)"
    }
   ]
  },
  {
   "title": "Top 10 Watched Movies",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"trakt_raw\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_event\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"movie\")\n  |> filter(fn: (r) => r[\"_field\"] == \"title\" or r[\"_field\"] == \"trakt_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"title\"])\n  |> count(column: \"trakt_id\")\n  |> group()\n  |> rename(columns: {\"title\": \"Movie\", \"trakt_id\": \"Plays\"})\n  |> keep(columns: [\"Movie\", \"Plays\"])\n  |> sort(columns: [\"Plays\"], desc: true)\n  |> limit(n: 10)"
    }
   ]
  },
  {
   "title": "Recently Watched Episodes",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"trakt_raw\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_event\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"episode\")\n  |> filter(fn: (r) => r[\"_field\"] == \"show_title\" or r[\"_field\"] == \"title\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 10)\n  |> keep(columns: [\"_time\", \"show_title\", \"title\"])\n  |> rename(columns: {\"_time\": \"Time\", \"show_title\": \"Show\", \"title\": \"Episode\"})"
    }
   ]
  },
  {
   "title": "Recently Watched Movies",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"trakt_raw\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"watch_event\")\n  |> filter(fn: (r) => r[\"media_type\"] == \"movie\")\n  |> filter(fn: (r) => r[\"_field\"] == \"title\")\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 10)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {\"_time\": \"Time\", \"_value\": \"Movie\"})"
    }
   ]
  }
 ]
}